// env-config.js
// File ini di-generate otomatis oleh Vercel dari Environment Variables
// JANGAN edit manual — set credentials di Vercel Dashboard → Settings → Environment Variables

window.ENV = {
  FIREBASE_API_KEY:             "VITE_FIREBASE_API_KEY_PLACEHOLDER",
  FIREBASE_AUTH_DOMAIN:         "VITE_FIREBASE_AUTH_DOMAIN_PLACEHOLDER",
  FIREBASE_DATABASE_URL:        "VITE_FIREBASE_DATABASE_URL_PLACEHOLDER",
  FIREBASE_PROJECT_ID:          "VITE_FIREBASE_PROJECT_ID_PLACEHOLDER",
  FIREBASE_STORAGE_BUCKET:      "VITE_FIREBASE_STORAGE_BUCKET_PLACEHOLDER",
  FIREBASE_MESSAGING_SENDER_ID: "VITE_FIREBASE_MESSAGING_SENDER_ID_PLACEHOLDER",
  FIREBASE_APP_ID:              "VITE_FIREBASE_APP_ID_PLACEHOLDER",
  GROQ_API_KEY:                 "VITE_GROQ_API_KEY_PLACEHOLDER"
};
